version: "3"

services:
  postgres:
    image: postgres
    container_name: student_db
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  backend:
    build: .
    container_name: zkp_backend
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - DB_HOST=student_db
      - DB_PORT=${DB_PORT}
      - PORT=8080
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
